using System.Diagnostics.CodeAnalysis;

namespace App.Interop;

/// <summary>
/// Bit flags for <see cref="WinEventSpec.Flags"/>, mirroring the
/// <c>WINEVENT_*</c> constants accepted by
/// <c>SetWinEventHook</c>.
/// </summary>
/// <remarks>
/// <para>
/// The default <see cref="OutOfContext"/> (value <c>0</c>) is the only safe
/// mode for an out-of-process subscriber — the OS delivers callbacks as
/// ordinary window messages on the registering thread rather than
/// injecting Stagehand's DLL into every event-producing process.
/// </para>
/// <para>
/// <see cref="SkipOwnThread"/> and <see cref="SkipOwnProcess"/> suppress
/// callbacks for events generated by the hook's own thread / process —
/// useful when a WinEvent subscriber also mutates windows itself and
/// wants to avoid feedback loops.
/// </para>
/// <para>
/// <see cref="InContext"/> injects Stagehand's DLL into the source
/// process; we never want this, but the flag is included for API
/// completeness so tests can reject it deliberately.
/// </para>
/// <para>
/// See <see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-setwineventhook"/>.
/// </para>
/// </remarks>
[Flags]
[SuppressMessage(
    "Design",
    "CA1028:Enum storage should be Int32",
    Justification = "Underlying storage is uint to exactly mirror the Win32 WINEVENT_* constants consumed by SetWinEventHook (which takes a UINT). Changing to int would force a cast in every P/Invoke call-site and risk sign-extension bugs."
)]
[SuppressMessage(
    "Naming",
    "CA1711:Identifiers should not have incorrect suffix",
    Justification = "Type name deliberately ends in 'Flags' to document its [Flags] shape and its mapping to Win32's WINEVENT_* bitmask. Renaming would lose that mapping."
)]
public enum WinEventFlags : uint
{
    /// <summary>
    /// <c>WINEVENT_OUTOFCONTEXT</c> (0x0000). Out-of-context delivery:
    /// callbacks arrive as messages on the hook-registering thread. The
    /// only safe mode for out-of-process subscribers such as Stagehand.
    /// Doubles as the zero-value member required by CA1008 (the OS treats
    /// 0 as the default, so giving it a domain name rather than "None"
    /// keeps call-sites self-documenting).
    /// </summary>
    [SuppressMessage(
        "Design",
        "CA1008:Enums should have zero value",
        Justification = "The zero value has a Win32-documented meaning (WINEVENT_OUTOFCONTEXT); renaming to 'None' would erase that."
    )]
    OutOfContext = 0x0000,

    /// <summary>
    /// <c>WINEVENT_SKIPOWNTHREAD</c> (0x0001). Skip events generated by
    /// the thread that installed the hook.
    /// </summary>
    SkipOwnThread = 0x0001,

    /// <summary>
    /// <c>WINEVENT_SKIPOWNPROCESS</c> (0x0002). Skip events generated by
    /// the process that installed the hook.
    /// </summary>
    SkipOwnProcess = 0x0002,

    /// <summary>
    /// <c>WINEVENT_INCONTEXT</c> (0x0004). In-context delivery — the OS
    /// injects the hook DLL into the source process. Incompatible with
    /// Stagehand's architecture; callers should never pass this.
    /// </summary>
    InContext = 0x0004,
}
