using System;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Threading;
using App.Services.Settings;
using App.Shell.Composition;
using App.Shell.Tray;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace App.Shell;

/// <summary>
/// WPF composition root. <see cref="Application.Main"/> is auto-generated by the
/// WPF SDK from <c>App.xaml</c>; this class boots the DI container, logging, and
/// the tray icon host. Named <c>ShellApp</c> (not <c>App</c>) so it does not
/// collide with the enclosing namespace segment <c>App</c> during C# name
/// resolution inside the WPF-generated <c>App.g.cs</c>.
/// </summary>
public partial class ShellApp : Application
{
    private static readonly Action<ILogger, bool, bool, Exception?> LogStarting =
        LoggerMessage.Define<bool, bool>(
            LogLevel.Information,
            new EventId(1001, nameof(LogStarting)),
            "Stagehand starting. Verbose={Verbose} DryRun={DryRun}"
        );

    private static readonly Action<ILogger, Exception?> LogShuttingDown = LoggerMessage.Define(
        LogLevel.Information,
        new EventId(1002, nameof(LogShuttingDown)),
        "Stagehand shutting down."
    );

    private static readonly Action<ILogger, Exception?> LogDomainUnhandled = LoggerMessage.Define(
        LogLevel.Critical,
        new EventId(1003, nameof(LogDomainUnhandled)),
        "Unhandled domain exception."
    );

    private static readonly Action<ILogger, Exception?> LogDispatcherUnhandled =
        LoggerMessage.Define(
            LogLevel.Critical,
            new EventId(1004, nameof(LogDispatcherUnhandled)),
            "Unhandled dispatcher exception."
        );

    private ServiceProvider? _services;
    private ILogger<ShellApp>? _log;

    /// <inheritdoc />
    protected override void OnStartup(StartupEventArgs e)
    {
        ArgumentNullException.ThrowIfNull(e);
        base.OnStartup(e);

        // IDE0042 (deconstruct) fights IDE0007/IDE0008 (var vs explicit) on
        // the deconstructed form — keep it as a named-tuple access instead.
#pragma warning disable IDE0042
        (bool verbose, bool dryRun, bool diagnostics) args = ParseArgs(e.Args);
#pragma warning restore IDE0042

        var paths = new AppDataSettingsPathProvider();

        var collection = new ServiceCollection();
        collection.AddSingleton<ISettingsPathProvider>(paths);
        collection.AddLogging(builder => builder.ConfigureStagehandLogging(paths));
        collection.ConfigureStagehand();

        _services = collection.BuildServiceProvider(
            new ServiceProviderOptions { ValidateOnBuild = true, ValidateScopes = true }
        );

        _log = _services.GetRequiredService<ILogger<ShellApp>>();
        LogStarting(_log, args.verbose, args.dryRun, null);

        AppDomain.CurrentDomain.UnhandledException += OnDomainUnhandledException;
        DispatcherUnhandledException += OnDispatcherUnhandledException;
        TaskScheduler.UnobservedTaskException += OnUnobservedTask;

        // Force settings load up front so file I/O failures surface before the
        // tray starts.
        _ = _services.GetRequiredService<ISettingsService>();

        TrayIconHost tray = _services.GetRequiredService<TrayIconHost>();
        tray.Start();

        if (args.diagnostics)
        {
            OpenLogsFolder(paths.LogDirectoryPath);
        }

        // ShutdownMode = OnExplicitShutdown is set in App.xaml; the app exits only
        // via TrayIconHost's "Exit" menu item.
    }

    /// <inheritdoc />
    protected override void OnExit(ExitEventArgs e)
    {
        if (_log is not null)
        {
            LogShuttingDown(_log, null);
        }
        _services?.Dispose();
        base.OnExit(e);
    }

    private static (bool Verbose, bool DryRun, bool Diagnostics) ParseArgs(string[] args)
    {
        bool verbose = false,
            dry = false,
            diag = false;
        foreach (var a in args)
        {
            if (a.Equals("--verbose", StringComparison.OrdinalIgnoreCase))
            {
                verbose = true;
            }
            else if (a.Equals("--dry-run", StringComparison.OrdinalIgnoreCase))
            {
                dry = true;
            }
            else if (a.Equals("--diagnostics", StringComparison.OrdinalIgnoreCase))
            {
                diag = true;
            }
        }
        return (verbose, dry, diag);
    }

    private static void OpenLogsFolder(string path)
    {
        try
        {
            // Use explorer.exe explicitly so behaviour does not depend on
            // whichever shell handler happens to be associated with directories.
            Process.Start(
                new ProcessStartInfo
                {
                    FileName = "explorer.exe",
                    Arguments = $"\"{path}\"",
                    UseShellExecute = false,
                }
            );
        }
        catch
        {
            // Best-effort; diagnostics opener is not critical to startup.
        }
    }

    private void OnDomainUnhandledException(object sender, UnhandledExceptionEventArgs e)
    {
        if (_log is not null)
        {
            LogDomainUnhandled(_log, e.ExceptionObject as Exception);
        }
    }

    private void OnDispatcherUnhandledException(
        object sender,
        DispatcherUnhandledExceptionEventArgs e
    )
    {
        if (_log is not null)
        {
            LogDispatcherUnhandled(_log, e.Exception);
        }
#if DEBUG
        // In Debug builds, let the exception propagate so the debugger can break
        // at the failure site. In Release builds, swallow and continue — the
        // system-tray app must not crash the user's desktop on a non-fatal error.
        // Plan 03 will add user-facing recovery (Plan 01 §Design.7).
#else
        e.Handled = true;
#endif
    }

    private static void OnUnobservedTask(object? sender, UnobservedTaskExceptionEventArgs e)
    {
        // Logger may not be available here; fall back to Debug.WriteLine.
        Debug.WriteLine($"Unobserved task exception: {e.Exception}");
        e.SetObserved();
    }
}
